### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by MTESTESTINGload** [syndiate/AutoFPCurator#2]
i would like that v3 now please

**Comment by syndiate** [comment]
@MTESTESTINGload 
[RELEASE_UNPACK_INSTANCE.zip](https://github.com/syndiate/AutoFPCurator/files/11559540/RELEASE_UNPACK_INSTANCE.zip)

**Comment by MTESTESTINGload** [comment]
got it

**Comment by syndiate** [comment]
Happy to help
